### ISSUE TITLE
Handle requests with ActivityPub media type in Accept header

### ISSUE THREAD

**Issue by silverpill** [immers-space/activitypub-express#82]
According to ActivityPub specification, servers should return ActivityStreams object representation in response to requests having `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` in Accept header, but Guppe only does that for `application/activity+json` media type.

>Servers ... MUST present the ActivityStreams object representation in response to application/ld+json; profile="https://www.w3.org/ns/activitystreams", and SHOULD also present the ActivityStreams representation in response to application/activity+json as well.

-- https://www.w3.org/TR/activitypub/#retrieving-objects

Example:

```shell
curl -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' https://a.gup.pe/u/3goodthings
```

This command returns 404 error page instead of the actor object.

**Comment by wmurphyrd** [comment]
Thanks, must have been a change in `type-is` since I setup [validators.jsonld](https://github.com/immers-space/activitypub-express/blob/master/net/validators.js#L149) (at the time it errored if profile was included but ignored it otherwise, so I had to truncate the comparison type to just `application/ld+json` to make it match), and I can see that my [units tests](https://github.com/immers-space/activitypub-express/blob/master/spec/functional/object.spec.js#L68) are inadequate to cover this case

**Comment by wmurphyrd** [comment]
Fix is deployed to Guppe now. Was this in relation to compatibility with a new fediverse app?

**Comment by silverpill** [comment]
The fix is working for actors. However, when I send `Follow()` activity to group inbox, it returns 404. This could be a different problem, but the server response looks similar. My request has `Content-Type` header with value `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`.

>Was this in relation to compatibility with a new fediverse app?

Yes, I noticed that my server doesn't federate properly with Guppe. Media type incompatibility is a common issue.

**Comment by wmurphyrd** [comment]
@silverpill please give it another try - updated again

**Comment by silverpill** [comment]
It's working. Thanks a lot!
